[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "0x6623fc72d1afe4f0b80338ebf99a2453d1e04c7f40f648bf425514785745701f"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
